--
-- Скрипт сгенерирован Devart dbForge Studio for SQL Server, Версия 5.5.327.0
-- Домашняя страница продукта: http://www.devart.com/ru/dbforge/sql/studio
-- Дата скрипта: 02.02.2018 23:40:55
-- Версия сервера: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT muzendis.dbo.Cities ON
GO
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (1, 1, N'Novosibirsk')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2, 1, N'Omsk')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (3, 2, N'Bijing')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (1003, 1002, N'Ombatyung')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2003, 1003, N'Caracas')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2004, 1003, N'Maracay')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2005, 1003, N'La Victoria')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2006, 1003, N'San Felipe')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2007, 1003, N'Puerto Cabello')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2008, 1003, N'Barquisimetro')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2009, 1003, N'Carora')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2010, 1003, N'Cabimas')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2011, 1003, N'Merida')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2012, 1003, N'Barinas')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2013, 1003, N'Maracaibo')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2014, 2002, N'Bogota')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2015, 2002, N'Ibague')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2016, 2002, N'Medelin')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2017, 2002, N'Espinal')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2018, 2002, N'Pereira')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2019, 2002, N'El Yopal')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2020, 2002, N'Cali')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2021, 2002, N'Florencia')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2022, 2002, N'Popayan')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2023, 2002, N'Neiva')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2024, 1002, N'Widhoek')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2025, 1002, N'Gobabis')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2026, 1002, N'Usakos')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2027, 1002, N'Arandis')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2028, 1002, N'Otjiwarongo')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2029, 1002, N'Khorixas')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2030, 1002, N'Oshaktai')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2031, 1002, N'Ondangwa')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2032, 1002, N'Grootfontein')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2033, 1002, N'Ruacana')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2034, 2003, N'Shimla')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2035, 2003, N'Delhi')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2036, 2003, N'Gurgaon')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2037, 2003, N'Rohtak')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2038, 2003, N'Hansi')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2039, 2003, N'Amroha')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2040, 2003, N'Rampur')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2041, 2003, N'Bareilly')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2042, 2003, N'Muazaffarnagar')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2043, 2003, N'Karnal')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2044, 2004, N'Astana')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2045, 2004, N'Kharaganda')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2046, 2004, N'Temirtau')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2047, 2004, N'Ekibastuz')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2048, 2004, N'Balkash')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2049, 2004, N'Taldhikorgan')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2050, 2004, N'Almata')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2051, 2004, N'Chemkent')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2052, 2004, N'Kizilorda')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2053, 2004, N'Baykonur')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2054, 2005, N'Reykjavík')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2055, 2005, N'Vík')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2056, 2005, N'Egilsstadir')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2057, 2005, N'Dalvík')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2058, 2005, N'Laugarbakki')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2059, 2005, N'Bildudalur')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2060, 2005, N'Keflavik')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2061, 2005, N'Selfoss')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2062, 2005, N'Thorlakshofn')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2063, 2005, N'Grindavík')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2064, 2006, N'Cienfuegos')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2065, 2006, N'La Habana')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2066, 2006, N'Pinar del Rio')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2067, 2006, N'Santa Clara')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2068, 2006, N'Sagua La Gran')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2069, 2006, N'Moron')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2070, 2006, N'Camaguey')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2071, 2006, N'Puerto Padre')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2072, 2006, N'Las Tunas')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2073, 2006, N'Guantanamo')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2074, 2006, N'Baracoa')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2075, 2007, N'Monterrey')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2076, 2007, N'Hermosillo')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2077, 2007, N'Tijuana')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2078, 2007, N'Ensenada')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2079, 2007, N'Guadalajara')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2080, 2007, N'Ciudad de Mexico')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2081, 2007, N'Veracruz')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2082, 2007, N'Merida')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2083, 2007, N'Playa del Carmen')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2084, 2007, N'Valladolid')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2085, 1, N'Krasnoyarsk')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2086, 1, N'Samara')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2087, 1, N'Norilsk')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2088, 1, N'Yakutsk')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2089, 1, N'Chita')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2090, 1, N'Mirniy')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2091, 1, N'Ayhal')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2092, 1, N'Perm')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2093, 1, N'Ufa')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2094, 2, N'Xi''an')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2095, 2, N'Chengdu')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2096, 2, N'Changsha')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2097, 2, N'Guangzhou')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2098, 2, N'Nanning')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2099, 2, N'Hong Kong')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2100, 2, N'Taipei')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2101, 2, N'Lhasa')
INSERT muzendis.dbo.Cities(Id, CountryId, Name) VALUES (2102, 2, N'Urumqi')
GO
SET IDENTITY_INSERT muzendis.dbo.Cities OFF
GO